### ISSUE TITLE
Please make a new tag

### ISSUE THREAD

**Issue by tsimonq2** [qtilities/sddm-conf#36]
It's over a year since a tag was made. I took the tip of the development branch and made a tarball (that's now in Ubuntu) on November 5th, but it would be good to get something tagged.

Let us know how we can help, and if there's anything left to complete before you're ready to tag.

Thank you!

**Comment by redtide** [comment]
Hello,
No objections here, I added only some minor things since then, but new translations alone would deserve it.
The only thing I'm not happy about is the poor [sddm configuration](https://man.archlinux.org/man/sddm.conf.5.en) handling, which I'm not sure I got how it works with multiple local configurations in `/etc/sddm.conf.d`.

**Comment by tsimonq2** [comment]
Sure, I have no issue waiting for that to land. If I find myself with spare time this week, I'd be happy to push some code your way.

Thanks for what you do!

Kind regards,
Simon Quigley
Lubuntu Release Manager

**Comment by redtide** [comment]
Let me know if you are still busy, we can postpone for another later release, it's not necessary to do that now.

**Comment by redtide** [comment]
tagged 0.2.0
